/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * shift tester 🧪
 * Апи для тестирования
 * OpenAPI spec version: 1.0
 */
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';
import { useMutation, useQuery } from '@tanstack/react-query';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

import { api } from '@/utils/api/instance';

export interface SessionResponse {
  /**
   * Причина ошибки
   * @nullable
   */
  reason?: string | null;
  /** Статус запроса */
  success: boolean;
  /** Пользователь */
  user: User;
}

export interface UpdateProfileResponse {
  /**
   * Причина ошибки
   * @nullable
   */
  reason?: string | null;
  /** Статус запроса */
  success: boolean;
  /** Пользователь */
  user: User;
}

export interface UpdateProfileProfileDto {
  /**
   * Город
   * @nullable
   */
  city: string | null;
  /**
   * Почта
   * @nullable
   */
  email: string | null;
  /**
   * Имя
   * @nullable
   */
  firstname: string | null;
  /**
   * Фамилия
   * @nullable
   */
  lastname: string | null;
}

export interface UpdateProfileDto {
  /** Номер телефона */
  phone: string;
  /** Данные пользователя */
  profile: UpdateProfileProfileDto;
}

export interface User {
  /** Город */
  city?: string;
  /** Почта */
  email?: string;
  /** Имя */
  firstname?: string;
  /** Фамилия */
  lastname?: string;
  /** Отчество */
  middlename?: string;
  /** Номер телефона */
  phone: string;
}

export interface SignInResponse {
  /**
   * Причина ошибки
   * @nullable
   */
  reason?: string | null;
  /** Статус запроса */
  success: boolean;
  /** Пользовательский токен */
  token: string;
  /** Пользователь */
  user: User;
}

export interface SignInDto {
  /** Отп код */
  code: number;
  /** Номер телефона */
  phone: string;
}

export interface OtpResponse {
  /**
   * Причина ошибки
   * @nullable
   */
  reason?: string | null;
  /** Время запроса повторного отп кода в мс */
  retryDelay: number;
  /** Статус запроса */
  success: boolean;
}

export interface CreateOtpDto {
  phone: string;
}

/**
 * @summary создание отп кода
 */
export const otpsControllerCreateOtp = (
  createOtpDto: CreateOtpDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<OtpResponse>> => {
  return api.post(`/auth/otp`, createOtpDto, options);
};

export const getOtpsControllerCreateOtpMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof otpsControllerCreateOtp>>,
    TError,
    { data: CreateOtpDto },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof otpsControllerCreateOtp>>,
  TError,
  { data: CreateOtpDto },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof otpsControllerCreateOtp>>,
    { data: CreateOtpDto }
  > = (props) => {
    const { data } = props ?? {};

    return otpsControllerCreateOtp(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type OtpsControllerCreateOtpMutationResult = NonNullable<
  Awaited<ReturnType<typeof otpsControllerCreateOtp>>
>;
export type OtpsControllerCreateOtpMutationBody = CreateOtpDto;
export type OtpsControllerCreateOtpMutationError = AxiosError<unknown>;

/**
 * @summary создание отп кода
 */
export const useOtpsControllerCreateOtp = <
  TError = AxiosError<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof otpsControllerCreateOtp>>,
    TError,
    { data: CreateOtpDto },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationResult<
  Awaited<ReturnType<typeof otpsControllerCreateOtp>>,
  TError,
  { data: CreateOtpDto },
  TContext
> => {
  const mutationOptions = getOtpsControllerCreateOtpMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * @summary авторизация
 */
export const usersControllerSignin = (
  signInDto: SignInDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<SignInResponse>> => {
  return api.post(`/users/signin`, signInDto, options);
};

export const getUsersControllerSigninMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerSignin>>,
    TError,
    { data: SignInDto },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerSignin>>,
  TError,
  { data: SignInDto },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerSignin>>,
    { data: SignInDto }
  > = (props) => {
    const { data } = props ?? {};

    return usersControllerSignin(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UsersControllerSigninMutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerSignin>>
>;
export type UsersControllerSigninMutationBody = SignInDto;
export type UsersControllerSigninMutationError = AxiosError<unknown>;

/**
 * @summary авторизация
 */
export const useUsersControllerSignin = <
  TError = AxiosError<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerSignin>>,
    TError,
    { data: SignInDto },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerSignin>>,
  TError,
  { data: SignInDto },
  TContext
> => {
  const mutationOptions = getUsersControllerSigninMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * @summary обновить профиль пользователя
 */
export const usersControllerUpdateProfile = (
  updateProfileDto: UpdateProfileDto,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<UpdateProfileResponse>> => {
  return api.patch(`/users/profile`, updateProfileDto, options);
};

export const getUsersControllerUpdateProfileMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUpdateProfile>>,
    TError,
    { data: UpdateProfileDto },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerUpdateProfile>>,
  TError,
  { data: UpdateProfileDto },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerUpdateProfile>>,
    { data: UpdateProfileDto }
  > = (props) => {
    const { data } = props ?? {};

    return usersControllerUpdateProfile(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UsersControllerUpdateProfileMutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerUpdateProfile>>
>;
export type UsersControllerUpdateProfileMutationBody = UpdateProfileDto;
export type UsersControllerUpdateProfileMutationError = AxiosError<unknown>;

/**
 * @summary обновить профиль пользователя
 */
export const useUsersControllerUpdateProfile = <
  TError = AxiosError<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUpdateProfile>>,
    TError,
    { data: UpdateProfileDto },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerUpdateProfile>>,
  TError,
  { data: UpdateProfileDto },
  TContext
> => {
  const mutationOptions = getUsersControllerUpdateProfileMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * @summary получить сессию пользователя
 */
export const usersControllerSession = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<SessionResponse>> => {
  return api.get(`/users/session`, options);
};

export const getUsersControllerSessionQueryKey = () => {
  return [`/users/session`] as const;
};

export const getUsersControllerSessionQueryOptions = <
  TData = Awaited<ReturnType<typeof usersControllerSession>>,
  TError = AxiosError<unknown>
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof usersControllerSession>>, TError, TData>
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUsersControllerSessionQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerSession>>> = ({ signal }) =>
    usersControllerSession({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerSession>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UsersControllerSessionQueryResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerSession>>
>;
export type UsersControllerSessionQueryError = AxiosError<unknown>;

/**
 * @summary получить сессию пользователя
 */
export const useUsersControllerSession = <
  TData = Awaited<ReturnType<typeof usersControllerSession>>,
  TError = AxiosError<unknown>
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof usersControllerSession>>, TError, TData>
  >;
  axios?: AxiosRequestConfig;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getUsersControllerSessionQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};
